# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 00:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FieldName', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Picture', models.ImageField(default='images', null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GuardianFirstName', models.CharField(blank=True, max_length=300, null=True, verbose_name='Guardian First Name')),
                ('GuardianLastName', models.CharField(blank=True, max_length=300, null=True, verbose_name='Guardian Last Name')),
                ('PlayerFirstName', models.CharField(max_length=300, verbose_name='Player First Name')),
                ('PlayerLastName', models.CharField(max_length=300, verbose_name='Player Last Name')),
                ('DateOfBirth', models.DateField(verbose_name='Date Of Birth')),
                ('Street', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=300)),
                ('State', models.CharField(max_length=300)),
                ('Zipcode', models.IntegerField(verbose_name='Zip Code')),
                ('PhoneNumber', models.CharField(help_text='Please use the following format: <em>555-555-5555</em>.', max_length=50, verbose_name='Phone Number')),
                ('Level', models.IntegerField(choices=[(0, ''), (1, 'PeeWee (Ages 8-10)'), (2, 'Minors (Ages 10-12)'), (3, 'Majors (Ages 12-14)')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositionDescrip', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.IntegerField(choices=[(0, ''), (1, '8:00 AM - 10:00 AM'), (2, '10:00 AM - 12:00 PM'), (3, '12:00 PM - 2:00 PM'), (4, '2:00 PM - 4:00 PM'), (5, '4:00 PM - 6:00 PM')], default=0)),
                ('FieldID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Field', verbose_name='Field')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(max_length=50)),
                ('Year', models.IntegerField()),
                ('DivisionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Division')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=300, verbose_name='First Name')),
                ('LastName', models.CharField(max_length=300, verbose_name='Last Name')),
                ('DateOfBirth', models.DateField(verbose_name='Date Of Birth')),
                ('Street', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=300)),
                ('State', models.CharField(max_length=300)),
                ('Zipcode', models.IntegerField(verbose_name='Zip Code')),
                ('PhoneNumber', models.CharField(help_text='Please use the following format: <em>555-555-5555</em>.', max_length=50, verbose_name='Phone Number')),
                ('Email', models.EmailField(max_length=300)),
                ('Returning', models.IntegerField(choices=[(0, ''), (1, 'Yes'), (2, 'No')], default=0)),
                ('Children', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('PositionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Position')),
                ('VolunteerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='VolunteerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Volunteer'),
        ),
        migrations.AddField(
            model_name='roster',
            name='TeamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='VolunteerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Volunteer', verbose_name='Coach'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set([('Date', 'Time', 'FieldID')]),
        ),
    ]
